"""Add price column

Revision ID: 2a3e679aa288
Revises: de89b61a3457
Create Date: 2023-04-04 10:05:14.561638-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3e679aa288'
down_revision = 'de89b61a3457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'total_price')
    # ### end Alembic commands ###
