"""Add price and description to Transport model

Revision ID: 35682716a224
Revises: fcab26b21dd1
Create Date: 2023-04-02 08:33:22.859602-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35682716a224'
down_revision = 'fcab26b21dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transport', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'price')
    op.drop_column('transport', 'description')
    # ### end Alembic commands ###
