"""Add InviteCode Model

Revision ID: 8be6900fef2f
Revises: b4221695462b
Create Date: 2023-04-02 06:05:22.281240-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be6900fef2f'
down_revision = 'b4221695462b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True, max_length=10),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_invite_code_id'), 'invite_code', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_code_id'), table_name='invite_code')
    op.drop_table('invite_code')
    # ### end Alembic commands ###
