"""Change taste_array to tast_dict

Revision ID: b4221695462b
Revises: e2bb728abcc2
Create Date: 2023-04-02 04:38:12.006968-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4221695462b'
down_revision = 'e2bb728abcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference', sa.Column('taste_dict', sa.JSON(), nullable=True))
    op.drop_column('preference', 'taste_array')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference', sa.Column('taste_array', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('preference', 'taste_dict')
    # ### end Alembic commands ###
