"""Add type column to transport

Revision ID: c73a42ef188e
Revises: 35682716a224
Create Date: 2023-04-03 03:40:49.988355-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73a42ef188e'
down_revision = '35682716a224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'type')
    # ### end Alembic commands ###
