"""Add type column to transport

Revision ID: d022fc79e4e1
Revises: c73a42ef188e
Create Date: 2023-04-03 03:44:47.050400-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd022fc79e4e1'
down_revision = 'c73a42ef188e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('transport_type', sa.String(), nullable=True))
    op.drop_column('transport', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transport', 'transport_type')
    # ### end Alembic commands ###
