"""Price column string

Revision ID: de89b61a3457
Revises: d022fc79e4e1
Create Date: 2023-04-03 04:20:34.382620-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de89b61a3457'
down_revision = 'd022fc79e4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
