"""Change preference taste column

Revision ID: e2bb728abcc2
Revises: 45f7a5c7f704
Create Date: 2023-04-02 04:15:10.871463-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bb728abcc2'
down_revision = '45f7a5c7f704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'preference', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preference', type_='foreignkey')
    # ### end Alembic commands ###
