"""Expand Package model

Revision ID: fcab26b21dd1
Revises: c05b56dadf90
Create Date: 2023-04-02 07:45:54.961787-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcab26b21dd1'
down_revision = 'c05b56dadf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('description', sa.String(), nullable=True))
    op.add_column('package', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('package', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('package', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'start_date')
    op.drop_column('package', 'end_date')
    op.drop_column('package', 'destination')
    op.drop_column('package', 'description')
    # ### end Alembic commands ###
